install.packages("gdata")
install.packages("party")
install.packages("partykit")
install.packages("caret")
install.packages("doParallel")

library(gdata)
library(tm)
library(KoNLP)
library(sqldf)
library(stringr)
library(party)
library(rpart)
library(partykit)
library(caret)
library(doParallel)
registerDoParallel(7)

